# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TimestripeCli < Formula
  desc "Command-line interface for Timestripe."
  homepage "https://github.com/timestripe/timestripe-cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timestripe/timestripe-cli/releases/download/v0.1.3/timestripe_0.1.3_macOS_x86_64.tar.gz"
      sha256 "6968509014be5a028c6ac02b16d570055fe08f29aa736bb94e97bba510cbeb2c"

      define_method(:install) do
        bin.install "timestripe"
        generate_completions_from_executable(bin/"timestripe", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timestripe/timestripe-cli/releases/download/v0.1.3/timestripe_0.1.3_macOS_arm64.tar.gz"
      sha256 "71c85c3bdddfd1d83d537dec89e76fadbcd737a8701ee37c095be4a2989f8f35"

      define_method(:install) do
        bin.install "timestripe"
        generate_completions_from_executable(bin/"timestripe", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/timestripe/timestripe-cli/releases/download/v0.1.3/timestripe_0.1.3_linux_x86_64.tar.gz"
      sha256 "e0e793942876d893e092ba1a6b74b0087d34129b07f440c1294704438146e309"
      define_method(:install) do
        bin.install "timestripe"
        generate_completions_from_executable(bin/"timestripe", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timestripe/timestripe-cli/releases/download/v0.1.3/timestripe_0.1.3_linux_arm64.tar.gz"
      sha256 "9e2f44f4c4656b5f6c2ce5200dcbe3f22c54392f620fd2f209622761ffaf4cb3"
      define_method(:install) do
        bin.install "timestripe"
        generate_completions_from_executable(bin/"timestripe", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/timestripe --version")
  end
end
