# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TimestripeCli < Formula
  desc "Command-line interface for Timestripe."
  homepage "https://github.com/timestripe/timestripe-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timestripe/timestripe-cli/releases/download/v0.1.1/timestripe_0.1.1_macOS_x86_64.tar.gz"
      sha256 "02359e6197e7c333d6211350d55cc609b4e2380db765f0c8d33a04a951ab0f1b"

      define_method(:install) do
        bin.install "timestripe"
        generate_completions_from_executable(bin/"timestripe", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timestripe/timestripe-cli/releases/download/v0.1.1/timestripe_0.1.1_macOS_arm64.tar.gz"
      sha256 "dabcdac19c64baf2e4b38b1f33f504437b7c2e4e70c61df66629a6535db5d53a"

      define_method(:install) do
        bin.install "timestripe"
        generate_completions_from_executable(bin/"timestripe", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/timestripe/timestripe-cli/releases/download/v0.1.1/timestripe_0.1.1_linux_x86_64.tar.gz"
      sha256 "bef1a5239869779851a9cc600fafb54533b19c10825e41220e34ee3d9632eac5"
      define_method(:install) do
        bin.install "timestripe"
        generate_completions_from_executable(bin/"timestripe", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timestripe/timestripe-cli/releases/download/v0.1.1/timestripe_0.1.1_linux_arm64.tar.gz"
      sha256 "e056566972033bf3f012500f2c49bd136d825b7aa0e0a09482031d589ac95032"
      define_method(:install) do
        bin.install "timestripe"
        generate_completions_from_executable(bin/"timestripe", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/timestripe --version")
  end
end
