# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timestripe < Formula
  desc "Command-line interface for Timestripe."
  homepage "https://github.com/timestripe/timestripe-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timestripe/timestripe-cli/releases/download/v0.1.0/timestripe_0.1.0_macOS_x86_64.tar.gz"
      sha256 "ca244c77fa23242ca7b53dad6625868d797055d9c315fb1ccd01c4e187089580"

      define_method(:install) do
        bin.install "timestripe"
        generate_completions_from_executable(bin/"timestripe", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timestripe/timestripe-cli/releases/download/v0.1.0/timestripe_0.1.0_macOS_arm64.tar.gz"
      sha256 "3a8d0ae0f6166c8a8c23dd578c1edac059d6987a28026542f9ec980785a0d8d4"

      define_method(:install) do
        bin.install "timestripe"
        generate_completions_from_executable(bin/"timestripe", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/timestripe/timestripe-cli/releases/download/v0.1.0/timestripe_0.1.0_linux_x86_64.tar.gz"
      sha256 "f57ccd8176e217bfd342a337d2ade8d8e47a193d5e4d570b62910649c69d9931"
      define_method(:install) do
        bin.install "timestripe"
        generate_completions_from_executable(bin/"timestripe", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timestripe/timestripe-cli/releases/download/v0.1.0/timestripe_0.1.0_linux_arm64.tar.gz"
      sha256 "0f0e629624ae72369b0f4f39f4c1e77d5316413b7182575bb62cd0ac9315ff12"
      define_method(:install) do
        bin.install "timestripe"
        generate_completions_from_executable(bin/"timestripe", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/timestripe --version")
  end
end
